# --- Seção do Service ---
# O Service expõe a aplicação para o mundo exterior e faz o balanceamento de carga.
apiVersion: v1
kind: Service
metadata:
  # Nome do Service.
  name: conversao-temperatura-service
spec:
  selector:
    # O Service encontra os Pods que têm este rótulo.
    app: conversao-temperatura
  type: LoadBalancer
  ports:
    - protocol: TCP
      # A porta que o Service vai expor. Você acessará a aplicação através desta porta.
      port: 80
      # A porta que o Service vai encaminhar para os containers.
      targetPort: 8080